### ISSUE TITLE
Equation to compute Estimates of mixed 4th moments

### ISSUE THREAD

**Issue by EnsioS** [lukejoconnor/LCV#1]
File **estimate_k4.m** estimation equations (lines 74-76)

`% Estimates of mixed 4th moments`
`k41=weighted_mean(nZ2.*nZ1.^3-3*nZ1.*nZ2*(intercept1/s1^2)-3*(nZ1.^2-intercept1/s1^2)*intercept12/s1/s2,weights);%/sum(nZ1.*nZ2)^2;`
`k42=weighted_mean(nZ1.*nZ2.^3-3*nZ1.*nZ2*(intercept2/s2^2)-3*(nZ2.^2-intercept2/s2^2)*intercept12/s1/s2,weights)`

seems to have different signs between some terms in sum than ones precented in article
https://www.biorxiv.org/content/biorxiv/early/2018/04/17/205435.full.pdf (equation 8 p. 16)
In article all terms in the sum has plus sign in front of them, but in code terms `-3*nZ1.*nZ2*(intercept1/s1^2)` and `-3*(nZ1.^2)*intercept12/s1/s2` has minus sign in front of them. So is there small error or have I misunderstood something? (I think this article provide quite little justification for steps of equation 8)

**Comment by lukejoconnor** [comment]
Hi EnsioS, sorry just getting back to you. Thanks for reading the code so carefully. Equation (8) in our paper has the form "E(uncorrected estimate)=truth+extra terms", and the code that you refer to has the form "corrected estimate <- uncorrected estimate - extra terms". Both the code and the paper are correct. By the way, you can derive Eq 8 using the formula for the cokurtosis of the normal distribution (i.e. see https://en.wikipedia.org/wiki/Cokurtosis).

Luke
