### ISSUE TITLE
A tutorial would be very helpful

### ISSUE THREAD

**Issue by HongyanR** [lukejoconnor/LCV#2]
Hi, I would very much like to use your algorithm to explore a few ideas I got in my mind. A simple tutorial could be much of great help to guide the user for the implementation. Is it possible for you post the code you used to analyze the UK traits in the NG paper? Thanks a lot!

**Comment by lukejoconnor** [comment]
Thanks for your interest. I'm not planning on publishing my data import and shell scripts, but I'd be happy to answer any specific questions - feel free to email me.
