### ISSUE TITLE
Example script in case of own ss data

### ISSUE THREAD

**Issue by jorientr** [lukejoconnor/LCV#4]
Thanks for posting scripts for this interesting method. I have been trying to run LCV on my own data but haven't been succesful so far. The example script seems to be based on a situation where you simulate data, which I don't want. I have prepared the three input files that the description says are needed: ell (LD scores), z.1 (effects on trait 1) & z.2 (effects on trait 2). I also ran the scripts RunLCV.R & MomentFunctions.R.  I then tried adapting the ExampleScript.R to run the RunLCV function on my own datasets but I get many different errors.

For, instance, is the below line correct to run the actual LCV model?
LCV<- RunLCV(ell,z.1,z.2,no.blocks,crosstrait.intercept,ldsc.intercept,weights,sig.threshold,N.1,N.2,intercept.12)

But this keeps giving me errors 'requires numeric/complex matrix/vector arguments' or 'undefined columns selected' 

Could you please provide some explanation? It would be perfect if you could upload a script with only the lines that are needed to run the LCV model, given that one has their own data (in the files ell, z.1 & z.2).

thanks!

**Comment by lukejoconnor** [comment]
Hi Jorien,
I've added a new example script (thanks to Katie Siewert for providing it). I also fixed a bug which might be causing your issue.

Luke
