### ISSUE TITLE
Zscore & CGP give opposite interpretations

### ISSUE THREAD

**Issue by jorientr** [lukejoconnor/LCV#5]
It would be great if you could help me out with this issue I've been having. I ran some LCV analyses and I'm a bit confused about the results. The zscore is positive (which according to the explanatory notes in the LCV script means that trait 1 causes trait 2), while the GCP statistic is negative (which according to the notes means that trait 2 causes trait 1). Looking at the p-values it seems that trait 1 is causal for trait 2 (which is in agreement with the zscore, but not with the GCP statistic).

Could you let me know what the right interpretation is for these results?

zscore = 5.84
gcp.pm = -0.82
gcp.pse = 0.14
rho.est = -0.17 
rho.err = 0.008
pval.fullycausal.1 = 7.4E-06
pval.fullycausal.2 = 0.951
h2.zscore.1 = 278.19
h2.zscore.2 = 165.81

**Comment by lukejoconnor** [comment]
I think this should be resolved in Mar 14 2019 bug fix.
